version: '3.8'

services:
  my_app:
    build:
      context: .
      dockerfile: single-stage.dockerfile
    expose:
      - '8080'
    deploy:
      replicas: 4
  proxy:
    image: nginx:latest
    ports: 
      - 8080:80
    depends_on:
      - my_app