version: '3.8'

services:
  my_app:
    build:
      context: .
      dockerfile: single-stage.dockerfile
    expose:
      - '8080'
    deploy:
      replicas: 4
    restart: always
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8080:80
    depends_on: 
      - my_app